# Generated by Django 4.2.6 on 2023-11-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='grid',
            field=models.JSONField(default=list),
        ),
    ]
