# Generated by Django 4.2.6 on 2023-11-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0002_game_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='grid',
        ),
    ]
