# Generated by Django 4.2.7 on 2023-11-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0003_remove_game_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='grid_data',
            field=models.JSONField(default='{"default": "value"}'),
        ),
    ]
