# Generated by Django 4.2.7 on 2023-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0004_game_grid_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='active_player',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='alignment',
            field=models.PositiveIntegerField(choices=[(1, 'Choice 1'), (2, 'Choice 2')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='grid_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
