# Generated by Django 4.2.7 on 2023-11-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0005_alter_game_active_player_alter_game_alignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='alignment',
            field=models.PositiveIntegerField(),
        ),
    ]
