# Generated by Django 4.2.7 on 2023-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0006_alter_game_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='waiting', max_length=10),
        ),
    ]
