# Generated by Django 4.2.7 on 2023-12-09 09:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0007_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
