# Generated by Django 4.2.7 on 2023-12-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0011_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
