# Generated by Django 4.2.7 on 2023-12-13 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('morpion', '0013_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='abandon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_abandoned', to=settings.AUTH_USER_MODEL),
        ),
    ]
