# Generated by Django 4.2.7 on 2023-12-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0014_game_abandon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='abandon',
            field=models.CharField(default='', max_length=20),
        ),
    ]
