# Generated by Django 4.2.7 on 2023-12-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0016_alter_game_abandon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
