# Generated by Django 4.2.7 on 2024-01-03 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0017_delete_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='alignment',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='grid_size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
