# Generated by Django 4.2.6 on 2023-11-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_game_symbol_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='game_symbol',
            field=models.ImageField(default='default_symbol.png', upload_to='game_symbols'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
