# Generated by Django 4.2.7 on 2023-12-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_game_symbol_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='game_symbol',
            field=models.ImageField(blank=True, null=True, upload_to='game_symbols'),
        ),
    ]
