# Generated by Django 4.2.7 on 2023-12-04 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueMorpion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille_grille', models.IntegerField()),
                ('alignement', models.IntegerField()),
                ('parties_jouees', models.IntegerField(default=0)),
                ('parties_gagnees', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatistiqueVictoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_victoires', models.IntegerField(default=0)),
                ('statistique_morpion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.statistiquemorpion')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='statistiquemorpion',
            name='gagnants',
            field=models.ManyToManyField(through='stats.StatistiqueVictoire', to=settings.AUTH_USER_MODEL),
        ),
    ]
