# Generated by Django 4.2.7 on 2023-12-04 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsMorpion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gris_size', models.IntegerField()),
                ('alignment', models.IntegerField()),
                ('game_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatsWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('stat_morpion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.statsmorpion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='statistiquevictoire',
            name='statistique_morpion',
        ),
        migrations.RemoveField(
            model_name='statistiquevictoire',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='StatistiqueMorpion',
        ),
        migrations.DeleteModel(
            name='StatistiqueVictoire',
        ),
        migrations.AddField(
            model_name='statsmorpion',
            name='winners',
            field=models.ManyToManyField(through='stats.StatsWin', to=settings.AUTH_USER_MODEL),
        ),
    ]
