# Generated by Django 4.2.7 on 2023-12-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_statsmorpion_statswin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statsmorpion',
            old_name='gris_size',
            new_name='grid_size',
        ),
    ]
