# Generated by Django 4.2.7 on 2023-12-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('morpion', '0008_game_winner'),
        ('stats', '0004_remove_statswin_stat_morpion_remove_statswin_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsMorpion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='morpion.game')),
            ],
        ),
    ]
