# Generated by Django 4.2.7 on 2023-12-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0009_alter_game_creator_alter_game_winner'),
        ('stats', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsmorpion',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morpion.game'),
        ),
    ]
