# Generated by Django 4.2.7 on 2023-12-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0009_alter_game_creator_alter_game_winner'),
        ('stats', '0006_alter_statsmorpion_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morpion.game', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StatsMorpion',
        ),
    ]
