# Generated by Django 4.2.7 on 2023-12-09 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0009_alter_game_creator_alter_game_winner'),
        ('stats', '0007_stats_delete_statsmorpion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='morpion.game'),
        ),
    ]
