# Generated by Django 4.2.7 on 2023-12-11 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_alter_stats_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='played_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
